server:
  port: 1002
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: cars
  config:
    import: optional:consul:/
  cloud:
    consul:
      host: localhost
      port: 8501
      discovery:
        health-check-path: /health
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
